forward_zone_file: /var/named/forward.zone
reverse_zone_file: /var/named/reverse.zone

dns_domain: prod.blackghost.lab
default_ip: 192.168.1.250
serial: 0

dns_records:
  - name: dns
    type: A
    value: 192.168.1.250
  - name: worklab-ad
    type: A
    value: 192.168.1.249
  - name: bg-mstr-01
    type: A
    value: 192.168.1.241
  - name: bg-mstr-02
    type: A
    value: 192.168.1.242
  - name: bg-mstr-03
    type: A
    value: 192.168.1.243
  - name: bg-boot
    type: A
    value: 192.168.1.244
  - name: bg-vsphere-01
    type: A
    value: 192.168.1.245
  - name: bg-work-01
    type: A
    value: 192.168.1.246
  - name: bg-ha-01
    type: A
    value: 192.168.1.247
  - name: api
    type: A
    value: 192.168.1.247
  - name: api-int
    type: A
    value: 192.168.1.247
  - name: '*.apps'
    type: A
    value: 192.168.1.247
  - name: ansible-controller
    type: A
    value: 192.168.1.248
  - name: vault
    type: A
    value: 192.168.1.251

dns_records_remove: []

reverse_dns_records:
  - ip: 192.168.1.250
    name: dns
  - ip: 192.168.1.249
    name: worklab-ad
  - ip: 192.168.1.241
    name: bg-mstr-01
  - ip: 192.168.1.242
    name: bg-mstr-02
  - ip: 192.168.1.243
    name: bg-mstr-03
  - ip: 192.168.1.244
    name: bg-boot
  - ip: 192.168.1.245
    name: bg-vsphere-01
  - ip: 192.168.1.246
    name: bg-work-01
  - ip: 192.168.1.247
    name: bg-ha-01
  - ip: 192.168.1.247
    name: api
  - ip: 192.168.1.247
    name: api-int
  - ip: 192.168.1.248
    name: ansible-controller
  - ip: 192.168.1.248
    name: vault
  - ip: 192.168.1.251


reverse_dns_records_remove: []
# Reverse network (first three octets)
reverse_zone_network: 1.168.192

